from __future__ import annotations

from typing import Protocol

from wechat_agent.domain.events import LifeEvent, LifeEventType
from wechat_agent.domain.memory import LongTermMemory
from wechat_agent.domain.messages import NormalizedMessage
from wechat_agent.domain.modes import ModeConfig
from wechat_agent.domain.tasks import ScheduledTask, TaskStatus


class MessageRepository(Protocol):
    def save(self, message: NormalizedMessage) -> None: ...
    def get(self, message_id: str) -> NormalizedMessage | None: ...
    def list_recent(self, user_id: str, limit: int) -> list[NormalizedMessage]: ...


class LifeEventRepository(Protocol):
    def save(self, event: LifeEvent) -> None: ...
    def list_for_user(
        self, user_id: str, event_type: LifeEventType | None = None
    ) -> list[LifeEvent]: ...


class MemoryRepository(Protocol):
    def save(self, memory: LongTermMemory) -> None: ...
    def get(self, memory_id: str) -> LongTermMemory | None: ...
    def list_active(self, user_id: str) -> list[LongTermMemory]: ...
    def replace(self, memory: LongTermMemory) -> None: ...


class ModeRepository(Protocol):
    def get(self, user_id: str) -> ModeConfig | None: ...
    def save(self, config: ModeConfig) -> None: ...


class TaskRepository(Protocol):
    def save(self, task: ScheduledTask) -> None: ...
    def list_due(self, user_id: str, now_iso: str) -> list[ScheduledTask]: ...
    def update_status(self, task_id: str, status: TaskStatus) -> None: ...
